[rules]
max_file_tokens = 2000
max_cyclomatic_complexity = 8
max_nesting_depth = 3
max_function_args = 5
max_function_words = 3
ignore_naming_on = []
ignore_tokens_on = [
    "Cargo.lock",
    "package-lock.json",
    "README.md",
    "/tests"
]

[rules.safety]
require_safety_comment = true
ban_unsafe = false

[rules.layers.definitions]

[rules.layers.allowed_deps]

[preferences]
theme = "Cyberpunk"
auto_copy = true
auto_format = false
system_bell = false
backup_retention = 5
progress_bars = true
require_plan = false

[commands]
fix = ["cargo fmt"]
check = [
    "cargo clippy --all-targets -- -D warnings -W clippy::pedantic",
    "cargo test",
]
